enter-queue: 'Time {time:.2f}: train {train.id} entering queue for {train.unload_time:.2f}h'
start-service: 'Time {time:.2f}: train {train.id} starting service for'
end-service: 'Time {time:.2f}: train {train.id} ending service for'
exit-queue: 'Time {time:.2f}: train {train.id} leaving queue'
